//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.MyDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoreInfoHorse
    {
        public int ID { get; set; }
        public Nullable<int> IdHorse { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> IndexBody { get; set; }
        public Nullable<int> TemperatureBody { get; set; }
        public Nullable<int> Puls { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Horse Horse { get; set; }
    }
}
