//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.MyDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SborMilk
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IdHorse { get; set; }
        public Nullable<int> IdBak { get; set; }
        public Nullable<int> IdKonsistention { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Bak Bak { get; set; }
        public virtual Horse Horse { get; set; }
        public virtual Konsistention Konsistention { get; set; }
        public virtual StatusSbora StatusSbora { get; set; }
    }
}
