//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumysnayaFermaKursach.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Breed
    {
        public Breed()
        {
            this.Horse = new HashSet<Horse>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Horse> Horse { get; set; }
    }
}
